import { makeStyles } from "tss-react/mui";

/*
 * @author Team-Beta
 * @Project React-App-Frontend
 * @Copyright (C) 2023 Newcastle University, UK
 */

export const useReviewStyles = makeStyles()(() => {
  return {
    main: {
      fontSize: "1.6rem",
    },
    modalHolderHidden: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      minWidth: "max-content",
      height: "100%",
      display: "flex",
      justifyContent: "center",
      visibility: "hidden",
      overflow: "auto",
      zIndex: "11",
    },
    modalHolderVisible: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      minWidth: "max-content",
      height: "100%",
      display: "flex",
      justifyContent: "center",
      visibility: "visible",
      overflow: "auto",
      zIndex: "11",
    },
    modalBackgroundHidden: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      backgroundColor: "rgb(28, 28, 28)",
      opacity: 0,
      visibility: "hidden",
      transition: "opacity 0.25s ease 0s",
    },
    modalBackgroundVisible: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      height: "100%",
      backgroundColor: "rgb(28, 28, 28)",
      opacity: 0.85,
      visibility: "visible",
      transition: "opacity 0.25s ease 0s",
    },
    modalMainHidden: {
      backgroundColor: "rgb(255, 255, 255)",
      height: "max-content",
      transform: "translate3d(0px, 0px, 0px)",
      opacity: 1,
      zIndex: 1,
      display: "flex",
      padding: "0px",
    },
    modalMainVisible: {
      backgroundColor: "rgb(255, 255, 255)",
      height: "max-content",
      transform: "translate3d(0px, 0px, 0px)",
      opacity: 1,
      zIndex: 1,
      display: "block",
      padding: "0px",
    },
    /* Section 1 start */
    addReviewHeaderMain: {
      width: "calc(100% - 4.6rem)",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      margin: "2rem 2.2rem 0px 2.4rem",
    },
    addReviewHeaderContent: {
      fontSize: "2.2rem",
      lineHeight: "2.8rem",
      fontWeight: "400",
      color: "rgb(28, 28, 28)",
      marginTop: "0.5rem",
      marginBottom: "0.83rem",
    },
    addReviewCloseButtonPrimary: {
      maxHeight: "3rem",
      height: "3rem",
      width: "3rem",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "50%",
      cursor: "pointer",
    },
    addReviewCloseButtonSecondary: {
      display: "inline-block",
      verticalAlign: "middle",
      lineHeight: "1",
      width: "24px",
      height: "24px",
    },
    /* Section 1 end */
    /* Section 2 start */
    addReviewHolderMain: {
      display: "block",
      overflow: "initial",
    },
    addReviewHolderInner: {
      margin: "0px",
      padding: "0px 1.4rem 2rem",
      width: "60rem",
    },
    addReviewRateExperienceContent: {
      fontSize: "1.6rem",
      lineHeight: "1.2",
      fontWeight: "400",
      color: "rgb(28, 28, 28)",
      margin: "0.8rem 0px 1.5rem",
    },
    /* Dining And Delievery Option start */
    dineAndDeliveryOptionMain: {
      width: "30%",
      marginTop: "1rem",
    },
    dineAndDeliveryOptionHolder: {
      display: "flex",
      justifyContent: "space-between",
    },
    optionHolder: {
      width: "max-content",
      marginBottom: "1.6rem",
      marginRight: "2.4rem",
    },
    optionLabel: {
      fontSize: "15px",
      color: "rgb(28, 28, 28)",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "start",
      height: "100%",
      lineHeight: "1.2",
    },
    optionSvg: {
      height: "2.2rem",
      widht: "2.2rem",
    },
    optionActiveOuterCircle: {
      stroke: "rgb(239, 79, 95)",
      strokeWidth: "1px",
      fill: "rgb(255, 255, 255)",
    },
    optionActiveInnerCircle: {
      fill: "rgb(239, 79, 95)",
    },
    optionInActiveCircle: {
      stroke: "rgb(156, 156, 156)",
      strokeWidth: "1px",
      fill: "rgb(255, 255, 255)",
      "&:hover": {
        stroke: "rgb(239, 79, 95)",
      },
    },
    optionContent: {
      paddingTop: "0.2rem",
      cursor: "pointer",
      color: "rgb(28, 28, 28)",
      margin: "0px 0px 0.1rem 0.8rem",
    },
    /* Dining And Delievery Option end */
    /* Writing Review section start */
    writeReviewContainer: {
      opacity: 1,
      pointerEvents: "all",
    },
    writeReviewMain: {
      marginTop: "2rem",
      display: "flex",
      justifyContent: "space-between",
    },
    imageHolderPrimary: {
      borderRadius: "50%",
    },
    imageHolderSecondary: {
      position: "relative",
      maxWidth: "100%",
      width: "4.4rem",
      height: "4.4rem",
      overflow: "hidden",
    },
    imageMain: {
      width: "100%",
      position: "absolute",
      top: "0px",
      left: "0px",
      height: "100%",
      background:
        "linear-gradient(to right, rgb(248, 248, 248) 0%, rgb(255, 255, 255) 10%, rgb(248, 248, 248) 40%, rgb(248, 248, 248) 100%) no-repeat rgb(248, 248, 248)",
      opacity: "0",
      transition: "opacity 0.25s ease-out 0s",
      willChange: "opacity",
      borderRadius: "inherit",
      animation: "1.5s linear 0s infinite normal forwards running jCOzbu",
    },
    image: {
      width: "100%",
      height: "100%",
      objectFit: "cover",
      transform: "none",
      opacity: 1,
      willChange: "transform, opacity",
      borderRadius: "inherit",
      filter: "unset",
      transition: "opacity 0.25s ease 0s, transform 0.25s ease 0s",
    },
    writeReviewHolder: {
      flexGrow: 1,
      marginLeft: "2rem",
    },
    writeReviewBoxMain: {
      position: "relative",
      width: "auto",
    },
    writeReviewBoxAreaInactive: {
      padding: "1.3rem 1.2rem",
      background: "rgb(255, 255, 255)",
      border: "0.1rem solid rgb(207, 207, 207)",
      fontSize: "18px",
      width: "100%",
      outline: "none",
      boxSizing: "border-box",
      borderRadius: "0.6rem",
      resize: "none",
      color: "rgb(28, 28, 28)",
      overflow: "hidden",
    },
    writeReviewBoxAreaActive: {
      padding: "1.25rem 1.15rem",
      background: "rgb(255, 255, 255)",
      border: "0.15rem solid rgb(17, 145, 153)",
      fontSize: "18px",
      width: "100%",
      outline: "none",
      boxSizing: "border-box",
      borderRadius: "0.6rem",
      resize: "none",
      color: "rgb(28, 28, 28)",
      overflow: "hidden",
    },
    writeReviewBoxLabelInactive: {
      position: "absolute",
      pointerEvents: "none",
      transition: "all 0.2s ease 0s",
      color: "rgb(181, 181, 181)",
      top: "13px",
      left: "14px",
      fontSize: "18px",
      background: "rgb(255, 255, 255)",
      padding: "0px",
    },
    writeReviewBoxLabelActive: {
      position: "absolute",
      pointerEvents: "none",
      transition: "all 0.2s ease 0s",
      color: "rgb(17, 145, 153)",
      top: "-5px",
      left: "25px",
      fontSize: "10px",
      background: "rgb(255, 255, 255)",
      padding: "0px 5px",
    },
    /* Writing Review section end */
    /* Submit Review section start */
    submitReviewContainer: {
      marginTop: "1.5rem",
      display: "flex",
      justifyContent: "flex-end",
    },
    submitReviewMain: {
      minWidth: "auto",
      minHeight: "36px",
      display: "inline-flex",
      alignItems: "strech",
      borderRadius: "0.6rem",
      background: "transparent",
      padding: "0px",
      border: "none",
      cursor: "none",
    },
    submitReviewSpanPrimary: {
      display: "inline-flex",
      verticalAlign: "center",
      alignItems: "center",
      justifyContent: "center",
      height: "100%",
      width: "100%",
      minWidth: "auto",
      minHeight: "36px",
      lineHeight: "36px",
      marginTop: "0px",
      marginLeft: "0px",
      whiteSpace: "nowrap",
      fontSize: "1rem",
      color: "rgb(239 79 95)",
      opacity: 1,
      background: "border-box transparent",
      borderColor: "rgb(255, 126, 139)",
      borderWidth: "0.1rem",
      borderStyle: "solid",
      borderRadius: "0.6rem",
      padding: "0px 1.6rem",
      transition:
        "transform 0.25s ease 0s, opacity 0.25s ease 0s, box-shadow 0.25s ease 0s",
      outline: "none !important",
    },
    submitReviewSpanSecondary: {
      display: "inline-block",
      verticalAlign: "middle",
      lineHeight: "normal",
      fontSize: "inherit",
      transition: "transform 0.4s ease 0s",
    },
    /* Submit Review section end */
    /* Section 2 end */
    "@media (min-width: 481px)": {
      modalMainHidden: {
        width: "max-content",
        margin: "5rem auto",
        minHeight: "150px",
        minWidth: "20rem",
        borderRadius: "0.6rem",
        transform: "scale(1.2)",
        boxShadow: "rgb(28 28 28 / 15%) 0px 1.2rem 7rem",
        transition: "transform 0.25s ease 0s",
      },
      modalMainVisible: {
        width: "max-content",
        margin: "5rem auto",
        minHeight: "150px",
        minWidth: "20rem",
        borderRadius: "0.6rem",
        transform: "scale(1)",
        boxShadow: "rgb(28 28 28 / 15%) 0px 1.2rem 7rem",
        transition: "transform 0.25s ease 0s",
      },
    },
  };
});
