import { createStyles, makeStyles } from "@mui/styles";

export const useReviewStyles = makeStyles(() =>
  createStyles({
    main: {
      fontSize: "1.6rem",
    },
    modalHolderHidden: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      minWidth: "max-content",
      height: "100%",
      display: "flex",
      justifyContent: "center",
      visibility: "hidden",
      overflow: "auto",
      zIndex: "11",
    },
    modalHolderVisible: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      minWidth: "max-content",
      height: "100%",
      display: "flex",
      justifyContent: "center",
      visibility: "visible",
      overflow: "auto",
      zIndex: "11",
    },
    modalBackgroundHidden: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      backgroundColor: "rgb(28, 28, 28)",
      opacity: 0,
      visibility: "hidden",
      transition: "opacity 0.25s ease 0s",
    },
    modalBackgroundVisible: {
      position: "fixed",
      top: "0px",
      left: "0px",
      width: "100%",
      backgroundColor: "rgb(28, 28, 28)",
      opacity: 0.85,
      visibility: "visible",
      transition: "opacity 0.25s ease 0s",
    },
    modalMainHidden: {
      backgroundColor: "rgb(255, 255, 255)",
      height: "max-content",
      transform: "translate3d(0px, 0px, 0px)",
      opacity: 1,
      zIndex: 1,
      display: "flex",
      padding: "0px",
    },
    modalMainVisible: {
      backgroundColor: "rgb(255, 255, 255)",
      height: "max-content",
      transform: "translate3d(0px, 0px, 0px)",
      opacity: 1,
      zIndex: 1,
      display: "block",
      padding: "0px",
    },
    /* Section 1 start */
    addReviewHeaderMain: {
      width: "calc(100% - 4.6rem)",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      margin: "2rem 2.2rem 0px 2.4rem",
    },
    addReviewHeaderContent: {
      fontSize: "2.2rem",
      lineHeight: "2.8rem",
      fontWeight: "400",
      color: "rgb(28, 28, 28)",
      marginTop: "0.5rem",
      marginBottom: "0.83rem",
    },
    addReviewCloseButtonPrimary: {
      maxHeight: "3rem",
      height: "3rem",
      width: "3rem",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "50%",
    },
    addReviewCloseButtonSecondary: {
      display: "inline-block",
      verticalAlign: "middle",
      lineHeight: "1",
      width: "24px",
      height: "24px",
    },
    /* Section 1 end */
    /* Section 2 start */
    addReviewHolderMain: {
      display: "block",
      overflow: "initial",
    },
    addReviewHolderInner: {
      margin: "0px",
      padding: "0px 1.4rem 2rem",
      width: "60rem",
    },
    addReviewRateExperienceContent: {
      fontSize: "1.6rem",
      lineHeight: "1.2",
      fontWeight: "400",
      color: "rgb(28, 28, 28)",
      margin: "0.8rem 0px 1.5rem",
    },
    dineAndDeliveryOptionMain: {
      width: "30%",
      marginTop: "1rem",
    },
    dineAndDeliveryOptionHolder: {
      display: "flex",
      justifyContent: "space-between",
    },
    optionHolder: {
      width: "max-content",
      marginBottom: "1.6rem",
      marginRight: "2.4rem",
    },
    optionLabel: {
      fontSize: "15px",
      color: "rgb(28, 28, 28)",
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      justifyContent: "start",
      height: "100%",
      lineHeight: "1.2",
    },
    optionSvg: {
      height: "2.2rem",
      widht: "2.2rem",
    },
    optionActiveOuterCircle: {
      stroke: "rgb(239, 79, 95)",
      strokeWidth: "1px",
      fill: "rgb(255, 255, 255)",
    },
    optionActiveInnerCircle: {
      fill: "rgb(239, 79, 95)",
    },
    optionInActiveCircle: {
      stroke: "rgb(156, 156, 156)",
      strokeWidth: "1px",
      fill: "rgb(255, 255, 255)",
      "&:hover": {
        stroke: "rgb(239, 79, 95)",
      },
    },
    optionContent: {
      paddingTop: "0.2rem",
      cursor: "pointer",
      color: "rgb(28, 28, 28)",
      margin: "0px 0px 0.1rem 0.8rem",
    },
    /* Section 2 end */
    "@media (min-width: 481px)": {
      modalMainHidden: {
        width: "max-content",
        margin: "5rem auto",
        minHeight: "150px",
        minWidth: "20rem",
        borderRadius: "0.6rem",
        transform: "scale(1.2)",
        boxShadow: "rgb(28 28 28 / 15%) 0px 1.2rem 7rem",
        transition: "transform 0.25s ease 0s",
      },
      modalMainVisible: {
        width: "max-content",
        margin: "5rem auto",
        minHeight: "150px",
        minWidth: "20rem",
        borderRadius: "0.6rem",
        transform: "scale(1)",
        boxShadow: "rgb(28 28 28 / 15%) 0px 1.2rem 7rem",
        transition: "transform 0.25s ease 0s",
      },
    },
  })
);
